### PR TITLE
changed localstorage to chrome storage

### PR DESCRIPTION
**Pull request by Croustys**
changed localstorage to chrome storage at most possible occasions. Let me know if you have any questions!

### CODE REVIEW

**Review by nicosh — CHANGES_REQUESTED** [review]
@Croustys  Thank you! 
Why in some places there are both local storage and chrome storage?

**Comment by Croustys** [comment]
I left it in the code so that you could have a look, so I could make sure I'm making the right changes. Also you don't lose anything perfomance-wise by having both local and chrome storage present, but I'll quickly remove the unnecessary parts as you wish!

**Comment by nicosh** [comment]
@Croustys the storage in the Notes section does not seems to work
I will fix it.

**Comment by Croustys** [comment]
I'm not quite sure what is causing the problem since it's working on my end, could you elaborate?
Thanks for your help

**Comment by nicosh** [comment]
@Croustys  i've fixed it in this way : 
```
        chrome.storage.local.get('notestext', (res) =>{
            let txt = res.notestext || "Write something..."
            setNotes(txt)
        });
```
Otherwise it will never load saved text.

**Pull request merged**
